import "./globals.css";
import Navbar from "@/components/Templates/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/Templates/Footer";
import Snackbar from "@/components/Templates/Snackbar";

export const metadata = {
  title: "Flight Way",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Snackbar>
          <Navbar />
          {children}
          <Footer />
        </Snackbar>
      </body>
    </html>
  );
}
