import "./globals.css";
import Navbar from "@/components/Templates/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/Templates/Footer";
import Snackbar from "@/components/Templates/Snackbar";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterMoment } from "@mui/x-date-pickers/AdapterMoment";
import ClientProvider from "@/components/Atom/LocalizationProvider";
// import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";

export const metadata = {
  title: "Flight Way",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <Snackbar>
            <Navbar />
            {children}
            <Footer />
          </Snackbar>
        </ClientProvider>
      </body>
    </html>
  );
}
